name: Funny PR Image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  funny-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i --no-audit --no-fund --silent

      - name: Build CLI
        run: npm run build --silent

      - name: Post witty image to PR (current branch build)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node dist/index.js \
            --repo "${{ github.repository }}" \
            --pr "${{ github.event.pull_request.number }}"