name: Publish to npm

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: publish-npm
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --silent

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version (minor) and push tag
        id: bump
        run: |
          NEW_VERSION=$(npm version minor -m "chore(release): %s [skip ci]")
          echo "version=${NEW_VERSION#v}" >> $GITHUB_OUTPUT
          git pull --rebase --autostash origin $(git rev-parse --abbrev-ref HEAD) || true
          git push --follow-tags origin HEAD

      - name: Build
        run: npm run build --silent

      - name: Prepare publish metadata
        id: prep
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "can_publish=false" >> $GITHUB_OUTPUT
            echo "Version $VERSION of $NAME already exists on npm. Skipping publish."
          else
            echo "can_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm (with provenance)
        if: steps.prep.outputs.can_publish == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}