name: Publish to npm

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --silent

      - name: Build
        run: npm run build --silent

      - name: Prepare publish metadata
        id: prep
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "can_publish=false" >> $GITHUB_OUTPUT
            echo "Version $VERSION of $NAME already exists on npm. Skipping publish."
          else
            echo "can_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm (with provenance)
        if: steps.prep.outputs.can_publish == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}